---
Name: versionedmodeladmin
Before: betterbuttons
Only:
    moduleexists: betterbuttons
---
SilverStripe\Forms\GridField\GridFieldDetailForm_ItemRequest:
  extensions:
    - VersionedGridFieldItemRequestExtension